/**
 * Embedded copy of PairMe's wine_vocab.csv (head/kind/country/parent/color/
 * grapes/tails/pronunciation/notes), the vocabulary wine_menu_lib.py loads
 * via Vocab.load() for appellation <-> grape resolution.
 *
 * Bundled as a plain JS array (not read from data/wine_vocab.csv at runtime)
 * because parseWineList.js has a fixed parseWineList(rawText) signature and
 * must work standalone in the browser with no fetch/fs step - see the
 * PairMe API Contract v1 note in parseWineList.js. data/wine_vocab.csv is
 * kept alongside the other reference CSVs for provenance/diffing; this file
 * is the one actually imported at runtime.
 *
 * Row shape matches Python's csv.DictReader(wine_vocab.csv) output exactly
 * (raw strings, un-normalised) so WineVocab.load() in wineVocab.js can
 * reproduce Vocab.load()'s own per-field parsing (splitting tails/grapes on
 * "|", trimming, etc) rather than pre-parsing here.
 */
export const WINE_VOCAB_ROWS =
[
  {
    "head": "nebbiolo",
    "kind": "grape",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "",
    "tails": "spanna|chiavennasca|picotener|picotendro|nebiolo|nebbiollo",
    "pronunciation": "neb-bee-OH-loh",
    "notes": ""
  },
  {
    "head": "barbera",
    "kind": "grape",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "",
    "tails": "barberra|barbara",
    "pronunciation": "bar-BEH-rah",
    "notes": ""
  },
  {
    "head": "dolcetto",
    "kind": "grape",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "",
    "tails": "dolceto",
    "pronunciation": "dol-CHET-toh",
    "notes": ""
  },
  {
    "head": "arneis",
    "kind": "grape",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "White",
    "grapes": "",
    "tails": "arnies",
    "pronunciation": "ar-NAYS",
    "notes": ""
  },
  {
    "head": "cortese",
    "kind": "grape",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "kor-TEH-zeh",
    "notes": ""
  },
  {
    "head": "timorasso",
    "kind": "grape",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "tee-moh-RAH-soh",
    "notes": ""
  },
  {
    "head": "corvina",
    "kind": "grape",
    "country": "Italy",
    "parent": "Veneto",
    "color": "Red",
    "grapes": "",
    "tails": "corvinone|corvina veronese",
    "pronunciation": "kor-VEE-nah",
    "notes": ""
  },
  {
    "head": "glera",
    "kind": "grape",
    "country": "Italy",
    "parent": "Veneto",
    "color": "Sparkling",
    "grapes": "",
    "tails": "prosecco tondo",
    "pronunciation": "GLEH-rah",
    "notes": ""
  },
  {
    "head": "garganega",
    "kind": "grape",
    "country": "Italy",
    "parent": "Veneto",
    "color": "White",
    "grapes": "",
    "tails": "grecanico|garganega di soave",
    "pronunciation": "gar-GAH-neh-gah",
    "notes": ""
  },
  {
    "head": "vermentino",
    "kind": "grape",
    "country": "Italy",
    "parent": "Liguria",
    "color": "White",
    "grapes": "",
    "tails": "pigato|favorita|rolle|vermentino di sardegna",
    "pronunciation": "ver-men-TEE-noh",
    "notes": ""
  },
  {
    "head": "friulano",
    "kind": "grape",
    "country": "Italy",
    "parent": "Friuli",
    "color": "White",
    "grapes": "",
    "tails": "tocai friulano|tocai|sauvignonasse|friulano tocai",
    "pronunciation": "free-oo-LAH-noh",
    "notes": ""
  },
  {
    "head": "ribolla gialla",
    "kind": "grape",
    "country": "Italy",
    "parent": "Friuli",
    "color": "White",
    "grapes": "",
    "tails": "ribolla|rebula|ribolla giala",
    "pronunciation": "ree-BOH-lah JAH-lah",
    "notes": ""
  },
  {
    "head": "malvasia",
    "kind": "grape",
    "country": "Italy",
    "parent": "",
    "color": "White",
    "grapes": "",
    "tails": "malvazija|malvasia istriana",
    "pronunciation": "mal-vah-ZEE-ah",
    "notes": ""
  },
  {
    "head": "verdicchio",
    "kind": "grape",
    "country": "Italy",
    "parent": "Marche",
    "color": "White",
    "grapes": "",
    "tails": "trebbiano di soave|verdichio",
    "pronunciation": "ver-DEE-kyoh",
    "notes": ""
  },
  {
    "head": "trebbiano",
    "kind": "grape",
    "country": "Italy",
    "parent": "",
    "color": "White",
    "grapes": "",
    "tails": "ugni blanc|procanico|trebiano",
    "pronunciation": "treb-bee-AH-noh",
    "notes": ""
  },
  {
    "head": "sangiovese",
    "kind": "grape",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "",
    "tails": "sangioveto|prugnolo gentile|morellino|nielluccio|sangiovesse|san giovese",
    "pronunciation": "san-joh-VEH-zeh",
    "notes": ""
  },
  {
    "head": "canaiolo",
    "kind": "grape",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "kah-nah-YOH-loh",
    "notes": ""
  },
  {
    "head": "sagrantino",
    "kind": "grape",
    "country": "Italy",
    "parent": "Umbria",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "sah-gran-TEE-noh",
    "notes": ""
  },
  {
    "head": "grechetto",
    "kind": "grape",
    "country": "Italy",
    "parent": "Umbria",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "greh-KET-toh",
    "notes": ""
  },
  {
    "head": "montepulciano",
    "kind": "grape",
    "country": "Italy",
    "parent": "Abruzzo",
    "color": "Red",
    "grapes": "",
    "tails": "montepulciano d abruzzo",
    "pronunciation": "mon-teh-pul-CHAH-noh",
    "notes": "ambiguous with the Tuscan town of Montepulciano"
  },
  {
    "head": "pecorino",
    "kind": "grape",
    "country": "Italy",
    "parent": "Abruzzo",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "peh-koh-REE-noh",
    "notes": "also a cheese; only trust inside wine text"
  },
  {
    "head": "passerina",
    "kind": "grape",
    "country": "Italy",
    "parent": "Marche",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "pas-seh-REE-nah",
    "notes": ""
  },
  {
    "head": "aglianico",
    "kind": "grape",
    "country": "Italy",
    "parent": "Campania",
    "color": "Red",
    "grapes": "",
    "tails": "agliannico",
    "pronunciation": "ah-LYAH-nee-koh",
    "notes": ""
  },
  {
    "head": "fiano",
    "kind": "grape",
    "country": "Italy",
    "parent": "Campania",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "fee-AH-noh",
    "notes": ""
  },
  {
    "head": "falanghina",
    "kind": "grape",
    "country": "Italy",
    "parent": "Campania",
    "color": "White",
    "grapes": "",
    "tails": "falangina",
    "pronunciation": "fah-lan-GHEE-nah",
    "notes": ""
  },
  {
    "head": "greco",
    "kind": "grape",
    "country": "Italy",
    "parent": "Campania",
    "color": "White",
    "grapes": "",
    "tails": "greco di tufo",
    "pronunciation": "GREH-koh",
    "notes": ""
  },
  {
    "head": "nerello mascalese",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sicily",
    "color": "Red",
    "grapes": "",
    "tails": "nerello|nerello cappuccio",
    "pronunciation": "neh-REL-loh mas-kah-LEH-zeh",
    "notes": ""
  },
  {
    "head": "nero d avola",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sicily",
    "color": "Red",
    "grapes": "",
    "tails": "nero davola|nero d'avola|calabrese",
    "pronunciation": "NEH-roh DAH-voh-lah",
    "notes": ""
  },
  {
    "head": "frappato",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sicily",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "frap-PAH-toh",
    "notes": ""
  },
  {
    "head": "carricante",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sicily",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "kar-ree-KAN-teh",
    "notes": ""
  },
  {
    "head": "grillo",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sicily",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "GREE-loh",
    "notes": ""
  },
  {
    "head": "catarratto",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sicily",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "kah-tar-RAT-toh",
    "notes": ""
  },
  {
    "head": "cannonau",
    "kind": "grape",
    "country": "Italy",
    "parent": "Sardinia",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "kan-noh-NOW",
    "notes": "same grape as grenache"
  },
  {
    "head": "lagrein",
    "kind": "grape",
    "country": "Italy",
    "parent": "Alto Adige",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "lah-GRINE",
    "notes": ""
  },
  {
    "head": "teroldego",
    "kind": "grape",
    "country": "Italy",
    "parent": "Trentino",
    "color": "Red",
    "grapes": "",
    "tails": "teroldego rotaliano",
    "pronunciation": "teh-ROL-deh-goh",
    "notes": ""
  },
  {
    "head": "schiava",
    "kind": "grape",
    "country": "Italy",
    "parent": "Alto Adige",
    "color": "Red",
    "grapes": "",
    "tails": "vernatsch|trollinger",
    "pronunciation": "ski-AH-vah",
    "notes": ""
  },
  {
    "head": "primitivo",
    "kind": "grape",
    "country": "Italy",
    "parent": "Puglia",
    "color": "Red",
    "grapes": "",
    "tails": "tribidrag|crljenak",
    "pronunciation": "pree-mee-TEE-voh",
    "notes": "same grape as zinfandel"
  },
  {
    "head": "negroamaro",
    "kind": "grape",
    "country": "Italy",
    "parent": "Puglia",
    "color": "Red",
    "grapes": "",
    "tails": "negro amaro",
    "pronunciation": "neh-groh-AH-mah-roh",
    "notes": ""
  },
  {
    "head": "lambrusco",
    "kind": "grape",
    "country": "Italy",
    "parent": "Emilia",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "lam-BROO-skoh",
    "notes": ""
  },
  {
    "head": "moscato",
    "kind": "grape",
    "country": "Italy",
    "parent": "",
    "color": "White",
    "grapes": "",
    "tails": "muscat|muscat blanc|moscatel|moscato d asti",
    "pronunciation": "mos-KAH-toh",
    "notes": ""
  },
  {
    "head": "cabernet sauvignon",
    "kind": "grape",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "",
    "tails": "cab sauv|cabernet|cab|cabernet sauvingon|cab sav",
    "pronunciation": "ka-ber-NAY so-vee-NYOHN",
    "notes": ""
  },
  {
    "head": "merlot",
    "kind": "grape",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "",
    "tails": "merlo",
    "pronunciation": "mer-LOH",
    "notes": ""
  },
  {
    "head": "cabernet franc",
    "kind": "grape",
    "country": "France",
    "parent": "Loire",
    "color": "Red",
    "grapes": "",
    "tails": "bouchet|breton|cab franc",
    "pronunciation": "ka-ber-NAY FRAHNK",
    "notes": ""
  },
  {
    "head": "petit verdot",
    "kind": "grape",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "peh-TEE ver-DOH",
    "notes": ""
  },
  {
    "head": "malbec",
    "kind": "grape",
    "country": "France",
    "parent": "Cahors",
    "color": "Red",
    "grapes": "",
    "tails": "cot|auxerrois|malbeck",
    "pronunciation": "mal-BEK",
    "notes": ""
  },
  {
    "head": "carmenere",
    "kind": "grape",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "",
    "tails": "carmenère|carmenere",
    "pronunciation": "kar-men-YEHR",
    "notes": ""
  },
  {
    "head": "semillon",
    "kind": "grape",
    "country": "France",
    "parent": "Bordeaux",
    "color": "White",
    "grapes": "",
    "tails": "sémillon",
    "pronunciation": "seh-mee-YOHN",
    "notes": ""
  },
  {
    "head": "sauvignon blanc",
    "kind": "grape",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "",
    "tails": "sauv blanc|savignon blanc|sauvignon blank",
    "pronunciation": "so-vee-NYOHN BLAHNK",
    "notes": ""
  },
  {
    "head": "chardonnay",
    "kind": "grape",
    "country": "France",
    "parent": "Burgundy",
    "color": "White",
    "grapes": "",
    "tails": "chard|chardonay|chardonnnay",
    "pronunciation": "shar-doh-NAY",
    "notes": ""
  },
  {
    "head": "pinot noir",
    "kind": "grape",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "",
    "tails": "pinot nero|spatburgunder|blauburgunder|pinot noire|pinot nior",
    "pronunciation": "PEE-noh NWAHR",
    "notes": ""
  },
  {
    "head": "pinot grigio",
    "kind": "grape",
    "country": "Italy",
    "parent": "",
    "color": "White",
    "grapes": "",
    "tails": "pinot gris|grauburgunder|rulander|pinot griggio",
    "pronunciation": "PEE-noh GREE-joh",
    "notes": ""
  },
  {
    "head": "gamay",
    "kind": "grape",
    "country": "France",
    "parent": "Beaujolais",
    "color": "Red",
    "grapes": "",
    "tails": "gamay noir",
    "pronunciation": "ga-MAY",
    "notes": ""
  },
  {
    "head": "syrah",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "",
    "tails": "shiraz|serine|sirah",
    "pronunciation": "see-RAH",
    "notes": ""
  },
  {
    "head": "grenache",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "",
    "tails": "garnacha|granacha|grenache noir",
    "pronunciation": "greh-NAHSH",
    "notes": ""
  },
  {
    "head": "mourvedre",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "",
    "tails": "monastrell|mataro|mourvèdre",
    "pronunciation": "moor-VEHD",
    "notes": ""
  },
  {
    "head": "carignan",
    "kind": "grape",
    "country": "France",
    "parent": "Languedoc",
    "color": "Red",
    "grapes": "",
    "tails": "carinena|mazuelo|carignane",
    "pronunciation": "kah-ree-NYAHN",
    "notes": ""
  },
  {
    "head": "cinsault",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "",
    "tails": "cinsaut",
    "pronunciation": "SAN-soh",
    "notes": ""
  },
  {
    "head": "viognier",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "White",
    "grapes": "",
    "tails": "vionnier|viogner",
    "pronunciation": "vee-oh-NYAY",
    "notes": ""
  },
  {
    "head": "marsanne",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "mar-SAHN",
    "notes": ""
  },
  {
    "head": "roussanne",
    "kind": "grape",
    "country": "France",
    "parent": "Rhone",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "roo-SAHN",
    "notes": ""
  },
  {
    "head": "picpoul",
    "kind": "grape",
    "country": "France",
    "parent": "Languedoc",
    "color": "White",
    "grapes": "",
    "tails": "piquepoul|picpoul de pinet",
    "pronunciation": "peek-POOL",
    "notes": ""
  },
  {
    "head": "chenin blanc",
    "kind": "grape",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "",
    "tails": "steen|pineau de la loire",
    "pronunciation": "SHEN-an BLAHNK",
    "notes": ""
  },
  {
    "head": "melon de bourgogne",
    "kind": "grape",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "",
    "tails": "muscadet grape",
    "pronunciation": "meh-LOHN duh boor-GOYN",
    "notes": ""
  },
  {
    "head": "riesling",
    "kind": "grape",
    "country": "Germany",
    "parent": "Mosel",
    "color": "White",
    "grapes": "",
    "tails": "rhine riesling|johannisberg riesling|reisling|rielsing",
    "pronunciation": "REES-ling",
    "notes": ""
  },
  {
    "head": "gewurztraminer",
    "kind": "grape",
    "country": "France",
    "parent": "Alsace",
    "color": "White",
    "grapes": "",
    "tails": "traminer|gewurtztraminer|gewürztraminer",
    "pronunciation": "geh-VURTS-trah-mee-ner",
    "notes": ""
  },
  {
    "head": "sylvaner",
    "kind": "grape",
    "country": "Germany",
    "parent": "",
    "color": "White",
    "grapes": "",
    "tails": "silvaner",
    "pronunciation": "sil-VAH-ner",
    "notes": ""
  },
  {
    "head": "gruner veltliner",
    "kind": "grape",
    "country": "Austria",
    "parent": "Wachau",
    "color": "White",
    "grapes": "",
    "tails": "gruner|grüner veltliner|gruener veltliner|gru ve",
    "pronunciation": "GROO-ner VELT-lee-ner",
    "notes": ""
  },
  {
    "head": "blaufrankisch",
    "kind": "grape",
    "country": "Austria",
    "parent": "Burgenland",
    "color": "Red",
    "grapes": "",
    "tails": "lemberger|kekfrankos|blaufränkisch",
    "pronunciation": "BLOW-fren-kish",
    "notes": ""
  },
  {
    "head": "zweigelt",
    "kind": "grape",
    "country": "Austria",
    "parent": "",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "TSVY-gelt",
    "notes": ""
  },
  {
    "head": "furmint",
    "kind": "grape",
    "country": "Hungary",
    "parent": "Tokaj",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "FOOR-mint",
    "notes": ""
  },
  {
    "head": "tempranillo",
    "kind": "grape",
    "country": "Spain",
    "parent": "Rioja",
    "color": "Red",
    "grapes": "",
    "tails": "tinto fino|tinta del pais|tinta roriz|aragonez|tempranilo",
    "pronunciation": "tem-prah-NEE-yoh",
    "notes": ""
  },
  {
    "head": "garnacha",
    "kind": "grape",
    "country": "Spain",
    "parent": "",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "gar-NAH-chah",
    "notes": "Spanish name for grenache"
  },
  {
    "head": "monastrell",
    "kind": "grape",
    "country": "Spain",
    "parent": "Jumilla",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "moh-nah-STREL",
    "notes": ""
  },
  {
    "head": "mencia",
    "kind": "grape",
    "country": "Spain",
    "parent": "Bierzo",
    "color": "Red",
    "grapes": "",
    "tails": "mencía",
    "pronunciation": "men-THEE-ah",
    "notes": ""
  },
  {
    "head": "albarino",
    "kind": "grape",
    "country": "Spain",
    "parent": "Rias Baixas",
    "color": "White",
    "grapes": "",
    "tails": "alvarinho|albariño|albarino",
    "pronunciation": "al-bah-REE-nyoh",
    "notes": ""
  },
  {
    "head": "verdejo",
    "kind": "grape",
    "country": "Spain",
    "parent": "Rueda",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "ver-DEH-hoh",
    "notes": ""
  },
  {
    "head": "godello",
    "kind": "grape",
    "country": "Spain",
    "parent": "Valdeorras",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "goh-DEH-yoh",
    "notes": ""
  },
  {
    "head": "palomino",
    "kind": "grape",
    "country": "Spain",
    "parent": "Jerez",
    "color": "White",
    "grapes": "",
    "tails": "palomino fino",
    "pronunciation": "pah-loh-MEE-noh",
    "notes": ""
  },
  {
    "head": "touriga nacional",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Douro",
    "color": "Red",
    "grapes": "",
    "tails": "touriga",
    "pronunciation": "too-REE-gah nah-syoh-NAHL",
    "notes": ""
  },
  {
    "head": "alvarinho",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Vinho Verde",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "al-vah-REE-nyoh",
    "notes": "Portuguese name for albarino"
  },
  {
    "head": "assyrtiko",
    "kind": "grape",
    "country": "Greece",
    "parent": "Santorini",
    "color": "White",
    "grapes": "",
    "tails": "asyrtiko|assyrtico",
    "pronunciation": "ah-SEER-tee-koh",
    "notes": ""
  },
  {
    "head": "xinomavro",
    "kind": "grape",
    "country": "Greece",
    "parent": "Naoussa",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "ksee-NOH-mah-vroh",
    "notes": ""
  },
  {
    "head": "agiorgitiko",
    "kind": "grape",
    "country": "Greece",
    "parent": "Nemea",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "ah-yor-YEE-tee-koh",
    "notes": ""
  },
  {
    "head": "zinfandel",
    "kind": "grape",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "",
    "tails": "zin",
    "pronunciation": "ZIN-fan-del",
    "notes": ""
  },
  {
    "head": "petite sirah",
    "kind": "grape",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "",
    "tails": "durif|petit sirah",
    "pronunciation": "peh-TEET see-RAH",
    "notes": ""
  },
  {
    "head": "pinotage",
    "kind": "grape",
    "country": "South Africa",
    "parent": "",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "PEE-noh-tahzh",
    "notes": ""
  },
  {
    "head": "tannat",
    "kind": "grape",
    "country": "Uruguay",
    "parent": "",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "tah-NAHT",
    "notes": ""
  },
  {
    "head": "barolo",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "nebbiolo",
    "tails": "barolo docg|barollo|barolo riserva",
    "pronunciation": "bah-ROH-loh",
    "notes": ""
  },
  {
    "head": "barbaresco",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "nebbiolo",
    "tails": "barbaresco docg|barberesco",
    "pronunciation": "bar-bah-RES-koh",
    "notes": ""
  },
  {
    "head": "langhe",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "nebbiolo|barbera|dolcetto",
    "tails": "langhe nebbiolo",
    "pronunciation": "LAHN-gheh",
    "notes": ""
  },
  {
    "head": "roero",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "White",
    "grapes": "arneis|nebbiolo",
    "tails": "roero arneis",
    "pronunciation": "roh-EH-roh",
    "notes": ""
  },
  {
    "head": "gattinara",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "nebbiolo",
    "tails": "",
    "pronunciation": "gat-tee-NAH-rah",
    "notes": ""
  },
  {
    "head": "barbera d alba",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "barbera",
    "tails": "barbera dalba|barbera d'alba",
    "pronunciation": "bar-BEH-rah DAHL-bah",
    "notes": ""
  },
  {
    "head": "barbera d asti",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "barbera",
    "tails": "barbera dasti|barbera d'asti",
    "pronunciation": "bar-BEH-rah DAH-stee",
    "notes": ""
  },
  {
    "head": "dolcetto d alba",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Red",
    "grapes": "dolcetto",
    "tails": "dolcetto dalba",
    "pronunciation": "dol-CHET-toh DAHL-bah",
    "notes": ""
  },
  {
    "head": "gavi",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "White",
    "grapes": "cortese",
    "tails": "cortese di gavi|gavi di gavi",
    "pronunciation": "GAH-vee",
    "notes": ""
  },
  {
    "head": "alta langa",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Piedmont",
    "color": "Sparkling",
    "grapes": "chardonnay|pinot noir",
    "tails": "",
    "pronunciation": "AHL-tah LAHN-gah",
    "notes": ""
  },
  {
    "head": "valtellina",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Lombardy",
    "color": "Red",
    "grapes": "nebbiolo",
    "tails": "valtellina superiore|sforzato|sfursat|inferno|grumello",
    "pronunciation": "val-tel-LEE-nah",
    "notes": ""
  },
  {
    "head": "franciacorta",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Lombardy",
    "color": "Sparkling",
    "grapes": "chardonnay|pinot noir",
    "tails": "",
    "pronunciation": "fran-chah-KOR-tah",
    "notes": ""
  },
  {
    "head": "lugana",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Lombardy",
    "color": "White",
    "grapes": "trebbiano",
    "tails": "",
    "pronunciation": "loo-GAH-nah",
    "notes": ""
  },
  {
    "head": "alto adige",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Alto Adige",
    "color": "White",
    "grapes": "pinot grigio|gewurztraminer|schiava",
    "tails": "sudtirol|südtirol|south tyrol",
    "pronunciation": "AHL-toh AH-dee-jeh",
    "notes": ""
  },
  {
    "head": "trentino",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Trentino",
    "color": "Sparkling",
    "grapes": "chardonnay|pinot noir",
    "tails": "trentodoc|trento doc",
    "pronunciation": "tren-TEE-noh",
    "notes": ""
  },
  {
    "head": "friuli",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Friuli",
    "color": "White",
    "grapes": "friulano|ribolla gialla|sauvignon blanc",
    "tails": "friuli colli orientali|colli orientali|friuli venezia giulia",
    "pronunciation": "free-OO-lee",
    "notes": ""
  },
  {
    "head": "collio",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Friuli",
    "color": "White",
    "grapes": "friulano|ribolla gialla",
    "tails": "",
    "pronunciation": "KOL-lyoh",
    "notes": ""
  },
  {
    "head": "carso",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Friuli",
    "color": "White",
    "grapes": "malvasia",
    "tails": "",
    "pronunciation": "KAR-soh",
    "notes": ""
  },
  {
    "head": "valpolicella",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Veneto",
    "color": "Red",
    "grapes": "corvina",
    "tails": "valpolicella ripasso|ripasso|valpolicella classico",
    "pronunciation": "val-poh-lee-CHEL-lah",
    "notes": ""
  },
  {
    "head": "amarone",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Veneto",
    "color": "Red",
    "grapes": "corvina",
    "tails": "amarone della valpolicella|amarone classico",
    "pronunciation": "ah-mah-ROH-neh",
    "notes": ""
  },
  {
    "head": "soave",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Veneto",
    "color": "White",
    "grapes": "garganega",
    "tails": "soave classico",
    "pronunciation": "SWAH-veh",
    "notes": ""
  },
  {
    "head": "prosecco",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Veneto",
    "color": "Sparkling",
    "grapes": "glera",
    "tails": "valdobbiadene|conegliano|prosecco superiore|prosseco",
    "pronunciation": "proh-SEK-koh",
    "notes": ""
  },
  {
    "head": "bardolino",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Veneto",
    "color": "Red",
    "grapes": "corvina",
    "tails": "",
    "pronunciation": "bar-doh-LEE-noh",
    "notes": ""
  },
  {
    "head": "chianti classico",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese",
    "tails": "chianti|gallo nero|chianti riserva|chianti rufina|cianti",
    "pronunciation": "kee-AHN-tee KLAS-see-koh",
    "notes": ""
  },
  {
    "head": "brunello di montalcino",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese",
    "tails": "brunello|montalcino|rosso di montalcino",
    "pronunciation": "broo-NEL-loh dee mon-tal-CHEE-noh",
    "notes": ""
  },
  {
    "head": "vino nobile di montepulciano",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese",
    "tails": "vino nobile|nobile di montepulciano",
    "pronunciation": "VEE-noh NOH-bee-leh",
    "notes": ""
  },
  {
    "head": "bolgheri",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "cabernet sauvignon|merlot|cabernet franc",
    "tails": "bolgheri superiore|bolgeri",
    "pronunciation": "bol-GEH-ree",
    "notes": ""
  },
  {
    "head": "maremma",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese",
    "tails": "maremma toscana",
    "pronunciation": "mah-REM-mah",
    "notes": ""
  },
  {
    "head": "carmignano",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese|cabernet sauvignon",
    "tails": "",
    "pronunciation": "kar-mee-NYAH-noh",
    "notes": ""
  },
  {
    "head": "morellino di scansano",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese",
    "tails": "morellino",
    "pronunciation": "moh-rel-LEE-noh",
    "notes": ""
  },
  {
    "head": "toscana",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Tuscany",
    "color": "Red",
    "grapes": "sangiovese|cabernet sauvignon|merlot",
    "tails": "tuscany|toscana igt|super tuscan|supertuscan|igt toscana",
    "pronunciation": "tos-KAH-nah",
    "notes": "the English-only spelling was the gap that lost Tignanello"
  },
  {
    "head": "montefalco",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Umbria",
    "color": "Red",
    "grapes": "sagrantino",
    "tails": "sagrantino di montefalco",
    "pronunciation": "mon-teh-FAL-koh",
    "notes": ""
  },
  {
    "head": "orvieto",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Umbria",
    "color": "White",
    "grapes": "grechetto|trebbiano",
    "tails": "",
    "pronunciation": "or-VYEH-toh",
    "notes": ""
  },
  {
    "head": "castelli di jesi",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Marche",
    "color": "White",
    "grapes": "verdicchio",
    "tails": "verdicchio dei castelli di jesi|jesi",
    "pronunciation": "kas-TEL-lee dee YEH-zee",
    "notes": ""
  },
  {
    "head": "montepulciano d abruzzo",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Abruzzo",
    "color": "Red",
    "grapes": "montepulciano",
    "tails": "abruzzo|montepulciano dabruzzo",
    "pronunciation": "mon-teh-pul-CHAH-noh dah-BROOT-soh",
    "notes": ""
  },
  {
    "head": "taurasi",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Campania",
    "color": "Red",
    "grapes": "aglianico",
    "tails": "",
    "pronunciation": "tow-RAH-zee",
    "notes": ""
  },
  {
    "head": "greco di tufo",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Campania",
    "color": "White",
    "grapes": "greco",
    "tails": "",
    "pronunciation": "GREH-koh dee TOO-foh",
    "notes": ""
  },
  {
    "head": "fiano di avellino",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Campania",
    "color": "White",
    "grapes": "fiano",
    "tails": "",
    "pronunciation": "fee-AH-noh dee ah-vel-LEE-noh",
    "notes": ""
  },
  {
    "head": "aglianico del vulture",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Basilicata",
    "color": "Red",
    "grapes": "aglianico",
    "tails": "vulture",
    "pronunciation": "ah-LYAH-nee-koh del VUL-too-reh",
    "notes": ""
  },
  {
    "head": "etna",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Sicily",
    "color": "Red",
    "grapes": "nerello mascalese|carricante",
    "tails": "etna rosso|etna bianco",
    "pronunciation": "ET-nah",
    "notes": ""
  },
  {
    "head": "cerasuolo di vittoria",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Sicily",
    "color": "Red",
    "grapes": "nero d avola|frappato",
    "tails": "vittoria",
    "pronunciation": "cheh-rah-SWOH-loh",
    "notes": ""
  },
  {
    "head": "sardinia",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Sardinia",
    "color": "Red",
    "grapes": "cannonau|vermentino",
    "tails": "sardegna|cannonau di sardegna",
    "pronunciation": "sar-DEE-nyah",
    "notes": ""
  },
  {
    "head": "salento",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Puglia",
    "color": "Red",
    "grapes": "primitivo|negroamaro",
    "tails": "puglia|manduria",
    "pronunciation": "sah-LEN-toh",
    "notes": ""
  },
  {
    "head": "champagne",
    "kind": "appellation",
    "country": "France",
    "parent": "Champagne",
    "color": "Sparkling",
    "grapes": "chardonnay|pinot noir",
    "tails": "blanc de blancs|blanc de noirs|champange",
    "pronunciation": "sham-PAYN",
    "notes": ""
  },
  {
    "head": "chablis",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "White",
    "grapes": "chardonnay",
    "tails": "chablis premier cru|chablis grand cru",
    "pronunciation": "shah-BLEE",
    "notes": ""
  },
  {
    "head": "bourgogne",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir|chardonnay",
    "tails": "burgundy|bourgogne rouge|bourgogne blanc|borgogne",
    "pronunciation": "boor-GOYN",
    "notes": ""
  },
  {
    "head": "meursault",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "White",
    "grapes": "chardonnay",
    "tails": "mersault",
    "pronunciation": "mer-SOH",
    "notes": ""
  },
  {
    "head": "puligny montrachet",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "White",
    "grapes": "chardonnay",
    "tails": "puligny|puligny-montrachet",
    "pronunciation": "poo-lee-NYEE mon-rah-SHAY",
    "notes": ""
  },
  {
    "head": "chassagne montrachet",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "White",
    "grapes": "chardonnay",
    "tails": "chassagne|chassagne-montrachet",
    "pronunciation": "shah-SAHN-yuh mon-rah-SHAY",
    "notes": ""
  },
  {
    "head": "gevrey chambertin",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "gevrey|gevrey-chambertin",
    "pronunciation": "zhev-RAY sham-ber-TAN",
    "notes": ""
  },
  {
    "head": "chambolle musigny",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "chambolle|chambolle-musigny",
    "pronunciation": "shahm-BOL moo-see-NYEE",
    "notes": ""
  },
  {
    "head": "vosne romanee",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "vosne|vosne-romanee",
    "pronunciation": "vone roh-mah-NAY",
    "notes": ""
  },
  {
    "head": "nuits saint georges",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "nuits st georges|nsg",
    "pronunciation": "nwee san ZHORZH",
    "notes": ""
  },
  {
    "head": "pommard",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "",
    "pronunciation": "poh-MAR",
    "notes": ""
  },
  {
    "head": "volnay",
    "kind": "appellation",
    "country": "France",
    "parent": "Burgundy",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "",
    "pronunciation": "vol-NAY",
    "notes": ""
  },
  {
    "head": "beaujolais",
    "kind": "appellation",
    "country": "France",
    "parent": "Beaujolais",
    "color": "Red",
    "grapes": "gamay",
    "tails": "morgon|fleurie|brouilly|moulin a vent|chiroubles|beaujolais villages",
    "pronunciation": "boh-zhoh-LAY",
    "notes": ""
  },
  {
    "head": "sancerre",
    "kind": "appellation",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "sauvignon blanc",
    "tails": "sancere",
    "pronunciation": "sahn-SEHR",
    "notes": ""
  },
  {
    "head": "pouilly fume",
    "kind": "appellation",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "sauvignon blanc",
    "tails": "pouilly-fume|pouilly fumé",
    "pronunciation": "poo-yee foo-MAY",
    "notes": ""
  },
  {
    "head": "vouvray",
    "kind": "appellation",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "chenin blanc",
    "tails": "",
    "pronunciation": "voo-VRAY",
    "notes": ""
  },
  {
    "head": "chinon",
    "kind": "appellation",
    "country": "France",
    "parent": "Loire",
    "color": "Red",
    "grapes": "cabernet franc",
    "tails": "bourgueil|saumur champigny",
    "pronunciation": "shee-NOHN",
    "notes": ""
  },
  {
    "head": "muscadet",
    "kind": "appellation",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "melon de bourgogne",
    "tails": "muscadet sevre et maine",
    "pronunciation": "moos-kah-DAY",
    "notes": ""
  },
  {
    "head": "savennieres",
    "kind": "appellation",
    "country": "France",
    "parent": "Loire",
    "color": "White",
    "grapes": "chenin blanc",
    "tails": "savennières",
    "pronunciation": "sah-ven-YEHR",
    "notes": ""
  },
  {
    "head": "bordeaux",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "cabernet sauvignon|merlot|cabernet franc",
    "tails": "bordeax|claret",
    "pronunciation": "bor-DOH",
    "notes": ""
  },
  {
    "head": "margaux",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "cabernet sauvignon|merlot",
    "tails": "",
    "pronunciation": "mar-GOH",
    "notes": ""
  },
  {
    "head": "pauillac",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "",
    "pronunciation": "poy-YAK",
    "notes": ""
  },
  {
    "head": "saint julien",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "st julien",
    "pronunciation": "san zhoo-LYAN",
    "notes": ""
  },
  {
    "head": "saint estephe",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "st estephe|saint-estephe",
    "pronunciation": "san tes-TEF",
    "notes": ""
  },
  {
    "head": "pomerol",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "merlot|cabernet franc",
    "tails": "",
    "pronunciation": "pom-eh-ROL",
    "notes": ""
  },
  {
    "head": "saint emilion",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Red",
    "grapes": "merlot|cabernet franc",
    "tails": "st emilion|saint-emilion",
    "pronunciation": "san teh-mee-LYOHN",
    "notes": ""
  },
  {
    "head": "sauternes",
    "kind": "appellation",
    "country": "France",
    "parent": "Bordeaux",
    "color": "Dessert",
    "grapes": "semillon|sauvignon blanc",
    "tails": "barsac",
    "pronunciation": "soh-TEHRN",
    "notes": ""
  },
  {
    "head": "cote rotie",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "syrah",
    "tails": "cote-rotie|côte rôtie",
    "pronunciation": "koht roh-TEE",
    "notes": ""
  },
  {
    "head": "hermitage",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "syrah",
    "tails": "crozes hermitage|crozes-hermitage",
    "pronunciation": "er-mee-TAHZH",
    "notes": ""
  },
  {
    "head": "cornas",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "syrah",
    "tails": "",
    "pronunciation": "kor-NAHSS",
    "notes": ""
  },
  {
    "head": "saint joseph",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "syrah",
    "tails": "st joseph",
    "pronunciation": "san zhoh-ZEF",
    "notes": ""
  },
  {
    "head": "chateauneuf du pape",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "grenache|syrah|mourvedre",
    "tails": "chateauneuf|cdp|chateauneuf-du-pape|châteauneuf",
    "pronunciation": "shah-toh-NUHF doo PAHP",
    "notes": ""
  },
  {
    "head": "gigondas",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Red",
    "grapes": "grenache",
    "tails": "vacqueyras|rasteau",
    "pronunciation": "zhee-gohn-DAHSS",
    "notes": ""
  },
  {
    "head": "tavel",
    "kind": "appellation",
    "country": "France",
    "parent": "Rhone",
    "color": "Rose",
    "grapes": "grenache",
    "tails": "lirac",
    "pronunciation": "tah-VEL",
    "notes": ""
  },
  {
    "head": "bandol",
    "kind": "appellation",
    "country": "France",
    "parent": "Provence",
    "color": "Red",
    "grapes": "mourvedre",
    "tails": "",
    "pronunciation": "bahn-DOL",
    "notes": ""
  },
  {
    "head": "provence",
    "kind": "appellation",
    "country": "France",
    "parent": "Provence",
    "color": "Rose",
    "grapes": "grenache|cinsault|syrah",
    "tails": "cotes de provence|cassis",
    "pronunciation": "proh-VAHNSS",
    "notes": ""
  },
  {
    "head": "languedoc",
    "kind": "appellation",
    "country": "France",
    "parent": "Languedoc",
    "color": "Red",
    "grapes": "syrah|grenache",
    "tails": "corbieres|faugeres|minervois|pic saint loup|roussillon",
    "pronunciation": "lahn-guh-DOK",
    "notes": ""
  },
  {
    "head": "alsace",
    "kind": "appellation",
    "country": "France",
    "parent": "Alsace",
    "color": "White",
    "grapes": "riesling|pinot gris|gewurztraminer",
    "tails": "",
    "pronunciation": "al-ZASS",
    "notes": ""
  },
  {
    "head": "jura",
    "kind": "appellation",
    "country": "France",
    "parent": "Jura",
    "color": "White",
    "grapes": "savagnin|chardonnay",
    "tails": "arbois|cotes du jura|vin jaune",
    "pronunciation": "zhoo-RAH",
    "notes": ""
  },
  {
    "head": "cahors",
    "kind": "appellation",
    "country": "France",
    "parent": "Cahors",
    "color": "Red",
    "grapes": "malbec",
    "tails": "",
    "pronunciation": "kah-OR",
    "notes": ""
  },
  {
    "head": "rioja",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Rioja",
    "color": "Red",
    "grapes": "tempranillo",
    "tails": "rioja alta|rioja alavesa|rioja reserva|rioja gran reserva",
    "pronunciation": "ree-OH-hah",
    "notes": ""
  },
  {
    "head": "ribera del duero",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Castilla",
    "color": "Red",
    "grapes": "tempranillo",
    "tails": "ribera",
    "pronunciation": "ree-BEH-rah del DWEH-roh",
    "notes": ""
  },
  {
    "head": "priorat",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Catalunya",
    "color": "Red",
    "grapes": "garnacha|carignan",
    "tails": "montsant",
    "pronunciation": "pree-oh-RAHT",
    "notes": ""
  },
  {
    "head": "bierzo",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Castilla",
    "color": "Red",
    "grapes": "mencia",
    "tails": "",
    "pronunciation": "BYEHR-thoh",
    "notes": ""
  },
  {
    "head": "rias baixas",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Galicia",
    "color": "White",
    "grapes": "albarino",
    "tails": "rías baixas|rias baixa",
    "pronunciation": "REE-ahs BYE-shahs",
    "notes": ""
  },
  {
    "head": "rueda",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Castilla",
    "color": "White",
    "grapes": "verdejo",
    "tails": "",
    "pronunciation": "RWEH-dah",
    "notes": ""
  },
  {
    "head": "toro",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Castilla",
    "color": "Red",
    "grapes": "tempranillo",
    "tails": "",
    "pronunciation": "TOH-roh",
    "notes": ""
  },
  {
    "head": "jumilla",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Murcia",
    "color": "Red",
    "grapes": "monastrell",
    "tails": "",
    "pronunciation": "hoo-MEE-yah",
    "notes": ""
  },
  {
    "head": "jerez",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Andalucia",
    "color": "Dessert",
    "grapes": "palomino",
    "tails": "sherry|fino|manzanilla|oloroso|amontillado|palo cortado",
    "pronunciation": "heh-RETH",
    "notes": ""
  },
  {
    "head": "cava",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Catalunya",
    "color": "Sparkling",
    "grapes": "macabeo|xarel lo|parellada",
    "tails": "penedes",
    "pronunciation": "KAH-vah",
    "notes": ""
  },
  {
    "head": "douro",
    "kind": "appellation",
    "country": "Portugal",
    "parent": "Douro",
    "color": "Red",
    "grapes": "touriga nacional",
    "tails": "",
    "pronunciation": "DOH-roo",
    "notes": ""
  },
  {
    "head": "porto",
    "kind": "appellation",
    "country": "Portugal",
    "parent": "Douro",
    "color": "Dessert",
    "grapes": "touriga nacional",
    "tails": "port|tawny port|vintage port|lbv",
    "pronunciation": "POR-too",
    "notes": ""
  },
  {
    "head": "vinho verde",
    "kind": "appellation",
    "country": "Portugal",
    "parent": "Minho",
    "color": "White",
    "grapes": "alvarinho",
    "tails": "vino verde",
    "pronunciation": "VEE-nyoo VEHR-deh",
    "notes": ""
  },
  {
    "head": "madeira",
    "kind": "appellation",
    "country": "Portugal",
    "parent": "Madeira",
    "color": "Dessert",
    "grapes": "verdelho|sercial|bual|malmsey",
    "tails": "madiera",
    "pronunciation": "mah-DEER-ah",
    "notes": ""
  },
  {
    "head": "verdelho",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Madeira",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "ver-DEL-yoo",
    "notes": ""
  },
  {
    "head": "sercial",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Madeira",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "SEHR-see-al",
    "notes": ""
  },
  {
    "head": "bual",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Madeira",
    "color": "White",
    "grapes": "",
    "tails": "boal",
    "pronunciation": "boo-AHL",
    "notes": ""
  },
  {
    "head": "malmsey",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Madeira",
    "color": "White",
    "grapes": "",
    "tails": "malvasia fina",
    "pronunciation": "MAHM-zee",
    "notes": ""
  },
  {
    "head": "mosel",
    "kind": "appellation",
    "country": "Germany",
    "parent": "Mosel",
    "color": "White",
    "grapes": "riesling",
    "tails": "mosel saar ruwer|moselle",
    "pronunciation": "MOH-zel",
    "notes": ""
  },
  {
    "head": "rheingau",
    "kind": "appellation",
    "country": "Germany",
    "parent": "Rheingau",
    "color": "White",
    "grapes": "riesling",
    "tails": "",
    "pronunciation": "RINE-gow",
    "notes": ""
  },
  {
    "head": "pfalz",
    "kind": "appellation",
    "country": "Germany",
    "parent": "Pfalz",
    "color": "White",
    "grapes": "riesling",
    "tails": "palatinate",
    "pronunciation": "FAHLTS",
    "notes": ""
  },
  {
    "head": "nahe",
    "kind": "appellation",
    "country": "Germany",
    "parent": "Nahe",
    "color": "White",
    "grapes": "riesling",
    "tails": "",
    "pronunciation": "NAH-uh",
    "notes": ""
  },
  {
    "head": "wachau",
    "kind": "appellation",
    "country": "Austria",
    "parent": "Wachau",
    "color": "White",
    "grapes": "gruner veltliner|riesling",
    "tails": "smaragd|federspiel",
    "pronunciation": "vah-KOW",
    "notes": ""
  },
  {
    "head": "kamptal",
    "kind": "appellation",
    "country": "Austria",
    "parent": "Kamptal",
    "color": "White",
    "grapes": "gruner veltliner",
    "tails": "kremstal",
    "pronunciation": "KAHMP-tahl",
    "notes": ""
  },
  {
    "head": "burgenland",
    "kind": "appellation",
    "country": "Austria",
    "parent": "Burgenland",
    "color": "Red",
    "grapes": "blaufrankisch",
    "tails": "",
    "pronunciation": "BOOR-gen-lahnt",
    "notes": ""
  },
  {
    "head": "santorini",
    "kind": "appellation",
    "country": "Greece",
    "parent": "Santorini",
    "color": "White",
    "grapes": "assyrtiko",
    "tails": "",
    "pronunciation": "san-toh-REE-nee",
    "notes": ""
  },
  {
    "head": "naoussa",
    "kind": "appellation",
    "country": "Greece",
    "parent": "Macedonia",
    "color": "Red",
    "grapes": "xinomavro",
    "tails": "",
    "pronunciation": "nah-OO-sah",
    "notes": ""
  },
  {
    "head": "nemea",
    "kind": "appellation",
    "country": "Greece",
    "parent": "Peloponnese",
    "color": "Red",
    "grapes": "agiorgitiko",
    "tails": "",
    "pronunciation": "NEH-mee-ah",
    "notes": ""
  },
  {
    "head": "tokaj",
    "kind": "appellation",
    "country": "Hungary",
    "parent": "Tokaj",
    "color": "Dessert",
    "grapes": "furmint",
    "tails": "tokaji|tokay|aszu",
    "pronunciation": "toh-KYE",
    "notes": ""
  },
  {
    "head": "napa valley",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "napa|oakville|rutherford|stags leap|howell mountain|spring mountain|mount veeder|calistoga|yountville|diamond mountain",
    "pronunciation": "NAP-uh",
    "notes": ""
  },
  {
    "head": "sonoma coast",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "pinot noir|chardonnay",
    "tails": "sonoma|russian river|russian river valley|rrv|carneros|alexander valley|dry creek|knights valley|chalk hill",
    "pronunciation": "soh-NOH-mah",
    "notes": ""
  },
  {
    "head": "anderson valley",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "mendocino",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "santa barbara",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "pinot noir|chardonnay",
    "tails": "sta rita hills|santa rita hills|santa maria|ballard canyon",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "paso robles",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "cabernet sauvignon|syrah",
    "tails": "",
    "pronunciation": "PAH-soh ROH-bulls",
    "notes": ""
  },
  {
    "head": "santa cruz mountains",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "pinot noir|cabernet sauvignon",
    "tails": "santa cruz",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "lodi",
    "kind": "appellation",
    "country": "USA",
    "parent": "California",
    "color": "Red",
    "grapes": "zinfandel",
    "tails": "sierra foothills",
    "pronunciation": "LOH-dye",
    "notes": ""
  },
  {
    "head": "willamette valley",
    "kind": "appellation",
    "country": "USA",
    "parent": "Oregon",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "willamette|dundee hills|eola amity|ribbon ridge|yamhill|chehalem",
    "pronunciation": "wil-LAM-it",
    "notes": ""
  },
  {
    "head": "columbia valley",
    "kind": "appellation",
    "country": "USA",
    "parent": "Washington",
    "color": "Red",
    "grapes": "cabernet sauvignon|syrah",
    "tails": "walla walla|red mountain|yakima|ancient lakes",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "finger lakes",
    "kind": "appellation",
    "country": "USA",
    "parent": "New York",
    "color": "White",
    "grapes": "riesling",
    "tails": "",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "colorado",
    "kind": "appellation",
    "country": "USA",
    "parent": "Colorado",
    "color": "Red",
    "grapes": "cabernet franc|merlot",
    "tails": "grand valley|west elks|palisade",
    "pronunciation": "",
    "notes": "the home-state lane Kirk will ask about"
  },
  {
    "head": "mendoza",
    "kind": "appellation",
    "country": "Argentina",
    "parent": "Mendoza",
    "color": "Red",
    "grapes": "malbec",
    "tails": "uco valley|lujan de cuyo|gualtallary|agrelo",
    "pronunciation": "men-DOH-sah",
    "notes": ""
  },
  {
    "head": "salta",
    "kind": "appellation",
    "country": "Argentina",
    "parent": "Salta",
    "color": "White",
    "grapes": "torrontes",
    "tails": "cafayate",
    "pronunciation": "SAHL-tah",
    "notes": ""
  },
  {
    "head": "maipo",
    "kind": "appellation",
    "country": "Chile",
    "parent": "Maipo",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "",
    "pronunciation": "MY-poh",
    "notes": ""
  },
  {
    "head": "colchagua",
    "kind": "appellation",
    "country": "Chile",
    "parent": "Rapel",
    "color": "Red",
    "grapes": "carmenere",
    "tails": "",
    "pronunciation": "kol-CHAH-gwah",
    "notes": ""
  },
  {
    "head": "casablanca",
    "kind": "appellation",
    "country": "Chile",
    "parent": "Aconcagua",
    "color": "White",
    "grapes": "sauvignon blanc",
    "tails": "limari|leyda",
    "pronunciation": "kah-sah-BLAHN-kah",
    "notes": ""
  },
  {
    "head": "marlborough",
    "kind": "appellation",
    "country": "New Zealand",
    "parent": "Marlborough",
    "color": "White",
    "grapes": "sauvignon blanc",
    "tails": "awatere|wairau",
    "pronunciation": "MARL-bur-uh",
    "notes": ""
  },
  {
    "head": "central otago",
    "kind": "appellation",
    "country": "New Zealand",
    "parent": "Otago",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "",
    "pronunciation": "oh-TAH-goh",
    "notes": ""
  },
  {
    "head": "hawkes bay",
    "kind": "appellation",
    "country": "New Zealand",
    "parent": "Hawkes Bay",
    "color": "Red",
    "grapes": "cabernet sauvignon|merlot",
    "tails": "hawke s bay|gimblett gravels",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "barossa valley",
    "kind": "appellation",
    "country": "Australia",
    "parent": "South Australia",
    "color": "Red",
    "grapes": "syrah",
    "tails": "barossa|eden valley",
    "pronunciation": "bah-ROSS-ah",
    "notes": ""
  },
  {
    "head": "mclaren vale",
    "kind": "appellation",
    "country": "Australia",
    "parent": "South Australia",
    "color": "Red",
    "grapes": "syrah|grenache",
    "tails": "",
    "pronunciation": "muh-KLAIR-en VALE",
    "notes": ""
  },
  {
    "head": "clare valley",
    "kind": "appellation",
    "country": "Australia",
    "parent": "South Australia",
    "color": "White",
    "grapes": "riesling",
    "tails": "",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "coonawarra",
    "kind": "appellation",
    "country": "Australia",
    "parent": "South Australia",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "",
    "pronunciation": "koo-nah-WAR-ah",
    "notes": ""
  },
  {
    "head": "margaret river",
    "kind": "appellation",
    "country": "Australia",
    "parent": "Western Australia",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "yarra valley",
    "kind": "appellation",
    "country": "Australia",
    "parent": "Victoria",
    "color": "Red",
    "grapes": "pinot noir",
    "tails": "yarra|mornington|adelaide hills|tasmania",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "stellenbosch",
    "kind": "appellation",
    "country": "South Africa",
    "parent": "Western Cape",
    "color": "Red",
    "grapes": "cabernet sauvignon",
    "tails": "franschhoek|constantia",
    "pronunciation": "STEL-en-bosh",
    "notes": ""
  },
  {
    "head": "swartland",
    "kind": "appellation",
    "country": "South Africa",
    "parent": "Western Cape",
    "color": "Red",
    "grapes": "syrah",
    "tails": "hemel en aarde|walker bay|elgin",
    "pronunciation": "SWART-lahnd",
    "notes": ""
  },
  {
    "head": "cerasuolo d abruzzo",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Abruzzo",
    "color": "Rose",
    "grapes": "montepulciano",
    "tails": "cerasuolo|cerasuolo dabruzzo",
    "pronunciation": "cheh-rah-SWOH-loh dah-BROOT-soh",
    "notes": "rose of montepulciano and NOT the Sicilian red"
  },
  {
    "head": "bugey",
    "kind": "appellation",
    "country": "France",
    "parent": "Savoie",
    "color": "Sparkling",
    "grapes": "gamay|poulsard",
    "tails": "bugey cerdon|cerdon",
    "pronunciation": "boo-ZHAY",
    "notes": ""
  },
  {
    "head": "savoie",
    "kind": "appellation",
    "country": "France",
    "parent": "Savoie",
    "color": "White",
    "grapes": "jacquere|altesse",
    "tails": "vin de savoie",
    "pronunciation": "sav-WAH",
    "notes": ""
  },
  {
    "head": "kremstal",
    "kind": "appellation",
    "country": "Austria",
    "parent": "Kremstal",
    "color": "White",
    "grapes": "gruner veltliner|riesling",
    "tails": "krems",
    "pronunciation": "KREMS-tahl",
    "notes": ""
  },
  {
    "head": "languedoc roussillon",
    "kind": "appellation",
    "country": "France",
    "parent": "Languedoc",
    "color": "Red",
    "grapes": "syrah|grenache|carignan",
    "tails": "languedoc-roussillon",
    "pronunciation": "lahn-guh-DOK roo-see-YOHN",
    "notes": ""
  },
  {
    "head": "campo de borja",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Aragon",
    "color": "Red",
    "grapes": "garnacha",
    "tails": "borja",
    "pronunciation": "KAHM-poh deh BOR-hah",
    "notes": ""
  },
  {
    "head": "amyndeon",
    "kind": "appellation",
    "country": "Greece",
    "parent": "Macedonia",
    "color": "Red",
    "grapes": "xinomavro",
    "tails": "amyndon|florina",
    "pronunciation": "ah-MEEN-deh-on",
    "notes": ""
  },
  {
    "head": "western cape",
    "kind": "appellation",
    "country": "South Africa",
    "parent": "Western Cape",
    "color": "Red",
    "grapes": "pinotage|syrah",
    "tails": "",
    "pronunciation": "",
    "notes": ""
  },
  {
    "head": "penedes",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Catalunya",
    "color": "Sparkling",
    "grapes": "xarel lo|macabeo|parellada",
    "tails": "classic penedes|corpinnat",
    "pronunciation": "peh-neh-DES",
    "notes": ""
  },
  {
    "head": "txakolina",
    "kind": "appellation",
    "country": "Spain",
    "parent": "Basque",
    "color": "White",
    "grapes": "hondarribi zuri",
    "tails": "getariako|txakoli|getaria",
    "pronunciation": "chah-koh-LEE-nah",
    "notes": ""
  },
  {
    "head": "bairrada",
    "kind": "appellation",
    "country": "Portugal",
    "parent": "Bairrada",
    "color": "Red",
    "grapes": "baga",
    "tails": "",
    "pronunciation": "by-RAH-dah",
    "notes": ""
  },
  {
    "head": "maule",
    "kind": "appellation",
    "country": "Chile",
    "parent": "Maule",
    "color": "Red",
    "grapes": "carignan|semillon",
    "tails": "",
    "pronunciation": "MOW-leh",
    "notes": ""
  },
  {
    "head": "emilia romagna",
    "kind": "appellation",
    "country": "Italy",
    "parent": "Emilia",
    "color": "Red",
    "grapes": "lambrusco",
    "tails": "emilia|grasparossa|castelvetro|salamino",
    "pronunciation": "eh-MEE-lyah roh-MAH-nyah",
    "notes": ""
  },
  {
    "head": "xarel lo",
    "kind": "grape",
    "country": "Spain",
    "parent": "Penedes",
    "color": "White",
    "grapes": "",
    "tails": "xarel-lo|xarello|xarel lo tinto",
    "pronunciation": "shah-REL-loh",
    "notes": ""
  },
  {
    "head": "macabeo",
    "kind": "grape",
    "country": "Spain",
    "parent": "Penedes",
    "color": "White",
    "grapes": "",
    "tails": "viura",
    "pronunciation": "mah-kah-BEH-oh",
    "notes": ""
  },
  {
    "head": "parellada",
    "kind": "grape",
    "country": "Spain",
    "parent": "Penedes",
    "color": "White",
    "grapes": "",
    "tails": "",
    "pronunciation": "pah-reh-YAH-dah",
    "notes": ""
  },
  {
    "head": "trepat",
    "kind": "grape",
    "country": "Spain",
    "parent": "Conca de Barbera",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "treh-PAHT",
    "notes": ""
  },
  {
    "head": "hondarribi zuri",
    "kind": "grape",
    "country": "Spain",
    "parent": "Basque",
    "color": "White",
    "grapes": "",
    "tails": "hondarribi belza|hondarribi",
    "pronunciation": "on-dah-REE-bee ZOO-ree",
    "notes": ""
  },
  {
    "head": "baga",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Bairrada",
    "color": "Red",
    "grapes": "",
    "tails": "",
    "pronunciation": "BAH-gah",
    "notes": ""
  },
  {
    "head": "nero di troia",
    "kind": "grape",
    "country": "Italy",
    "parent": "Puglia",
    "color": "Red",
    "grapes": "",
    "tails": "uva di troia",
    "pronunciation": "NEH-roh dee TROY-ah",
    "notes": ""
  },
  {
    "head": "jacquere",
    "kind": "grape",
    "country": "France",
    "parent": "Savoie",
    "color": "White",
    "grapes": "",
    "tails": "jacquère",
    "pronunciation": "zhah-KEHR",
    "notes": ""
  },
  {
    "head": "altesse",
    "kind": "grape",
    "country": "Portugal",
    "parent": "Savoie",
    "color": "White",
    "grapes": "",
    "tails": "roussette",
    "pronunciation": "al-TESS",
    "notes": ""
  }
];
